apiVersion: v1
entries:
  conntrack-ebpf-exporter:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2026-03-06T11:28:27.209136+07:00"
    description: A Helm chart for conntrack-ebpf-exporter — eBPF-based per-pod conntrack
      metrics exporter
    digest: 6f17e01c989301d019d5cd843ed59bcd5969553d9c3835b32e2240f49844b49e
    home: https://github.com/zufardhiyaulhaq/conntrack-ebpf-exporter
    keywords:
    - ebpf
    - conntrack
    - prometheus
    - exporter
    - kubernetes
    maintainers:
    - name: zufardhiyaulhaq
    name: conntrack-ebpf-exporter
    sources:
    - https://github.com/zufardhiyaulhaq/conntrack-ebpf-exporter
    type: application
    urls:
    - conntrack-ebpf-exporter-0.1.0.tgz
    version: 0.1.0
generated: "2026-03-06T11:28:27.208794+07:00"
