apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "conntrack-ebpf-exporter.fullname" . }}
  labels:
    {{- include "conntrack-ebpf-exporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "conntrack-ebpf-exporter.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "conntrack-ebpf-exporter.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
