//go:build linux

// This is a development stub for the types generated by bpf2go.
// It will be overwritten by `go generate` (which runs bpf2go) on a Linux machine.

package ebpf

import (
	"fmt"

	"github.com/cilium/ebpf"
)

type conntrackMapKey struct {
	NetnsInode uint32
	State      uint8
	Pad        [3]uint8
}

type conntrackPrograms struct {
	KprobeCtInsert *ebpf.Program `ebpf:"kprobe_ct_insert"`
	KprobeCtDelete *ebpf.Program `ebpf:"kprobe_ct_delete"`
}

func (p *conntrackPrograms) Close() error {
	var errs []error
	if p.KprobeCtInsert != nil {
		errs = append(errs, p.KprobeCtInsert.Close())
	}
	if p.KprobeCtDelete != nil {
		errs = append(errs, p.KprobeCtDelete.Close())
	}
	if len(errs) > 0 {
		return fmt.Errorf("closing programs: %v", errs)
	}
	return nil
}

type conntrackMaps struct {
	ConntrackCounts *ebpf.Map `ebpf:"conntrack_counts"`
}

func (m *conntrackMaps) Close() error {
	if m.ConntrackCounts != nil {
		return m.ConntrackCounts.Close()
	}
	return nil
}

type conntrackObjects struct {
	conntrackPrograms
	conntrackMaps
}

func (o *conntrackObjects) Close() error {
	var errs []error
	errs = append(errs, o.conntrackPrograms.Close())
	errs = append(errs, o.conntrackMaps.Close())
	for _, err := range errs {
		if err != nil {
			return err
		}
	}
	return nil
}

func loadConntrackObjects(obj *conntrackObjects, opts *ebpf.CollectionOptions) error {
	// Stub — real implementation is generated by bpf2go from the compiled BPF object.
	return fmt.Errorf("BPF objects not compiled — run 'make generate' on Linux first")
}
